# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fitting Simple Linear Models
#'
#' 'lm_cpp' is used to fit simple linear models.
#'
#' @param y a vector of response variable.
#' @param x a vector of predictor variable.
#'
#' @return coefficients a named vector of coefficients.
#' @return se the standard errors.
#' @return ci the 95% confidence intervals.
#' @return residuals the residuals, that is response minus fitted values.
#' @return fitted.values the fitted mean values.
#'
#' @export
#'
lm_cpp <- function(y, x) {
    .Call(`_SimpLinR_lm_cpp`, y, x)
}

